CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "IconClass" character varying(50),
        "DisplayOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedDate" timestamp without time zone,
        "DeletedBy" text,
        "CreatedDate" timestamp without time zone NOT NULL,
        "UpdatedDate" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "CompanySettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DisplayName" character varying(200) NOT NULL,
        "LegalName" character varying(200),
        "TaxNumber" character varying(80),
        "Address" character varying(500),
        "City" character varying(100),
        "Country" character varying(100),
        "Phone" character varying(40),
        "Email" character varying(256),
        "LogoPath" character varying(500),
        "InvoicePrefix" character varying(20) NOT NULL,
        "InvoiceFooterNote" character varying(1000),
        "CreatedDate" timestamp without time zone NOT NULL,
        "UpdatedDate" timestamp without time zone NOT NULL,
        "UpdatedBy" text,
        CONSTRAINT "PK_CompanySettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "Customers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Email" character varying(256),
        "Phone" character varying(20),
        "Address" character varying(500),
        "Notes" text,
        "LoyaltyPoints" integer NOT NULL,
        "TotalPurchases" numeric(18,2) NOT NULL,
        "VisitCount" integer NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedDate" timestamp without time zone,
        "DeletedBy" text,
        "CreatedDate" timestamp without time zone NOT NULL,
        "UpdatedDate" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "Discounts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "DiscountType" integer NOT NULL,
        "Value" numeric(18,2) NOT NULL,
        "MinOrderAmount" numeric(18,2),
        "MaxDiscountAmount" numeric(18,2),
        "UsageLimit" integer,
        "UsedCount" integer NOT NULL,
        "StartDate" timestamp without time zone,
        "EndDate" timestamp without time zone,
        "IsActive" boolean NOT NULL,
        "CreatedDate" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Discounts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "SupplierInvoices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "InvoiceNumber" character varying(50) NOT NULL,
        "SupplierInvoiceNumber" character varying(100),
        "SupplierName" character varying(200) NOT NULL,
        "SupplierTaxNumber" character varying(80),
        "SupplierAddress" character varying(500),
        "SupplierPhone" character varying(40),
        "SupplierEmail" character varying(256),
        "InvoiceDate" timestamp without time zone NOT NULL,
        "DueDate" timestamp without time zone,
        "SubTotal" numeric(18,2) NOT NULL,
        "TaxAmount" numeric(18,2) NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "Notes" character varying(1000),
        "Status" character varying(30) NOT NULL,
        "CreatedDate" timestamp without time zone NOT NULL,
        "CreatedBy" text,
        CONSTRAINT "PK_SupplierInvoices" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Description" text NOT NULL,
        "SKU" character varying(50),
        "Barcode" text,
        "Price" numeric(18,2) NOT NULL,
        "Stock" integer NOT NULL,
        "MinStock" integer NOT NULL,
        "ImagePath" text,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedDate" timestamp without time zone,
        "DeletedBy" text,
        "CreatedDate" timestamp without time zone NOT NULL,
        "UpdatedDate" timestamp without time zone NOT NULL,
        "CategoryId" integer,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "Sales" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SaleNumber" character varying(50) NOT NULL,
        "SaleDate" timestamp without time zone NOT NULL,
        "SubTotal" numeric(18,2) NOT NULL,
        "DiscountAmount" numeric(18,2) NOT NULL,
        "TaxAmount" numeric(18,2) NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "Status" text NOT NULL,
        "PaymentMethod" text NOT NULL,
        "CashierId" text,
        "CashierName" text,
        "CustomerId" integer,
        "DiscountId" integer,
        "DiscountCode" text,
        CONSTRAINT "PK_Sales" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sales_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "SupplierInvoiceItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SupplierInvoiceId" integer NOT NULL,
        "Description" character varying(300) NOT NULL,
        "Quantity" numeric(18,3) NOT NULL,
        "UnitCost" numeric(18,2) NOT NULL,
        "TaxRate" numeric(5,2) NOT NULL,
        "TaxAmount" numeric(18,2) NOT NULL,
        "LineTotal" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_SupplierInvoiceItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SupplierInvoiceItems_SupplierInvoices_SupplierInvoiceId" FOREIGN KEY ("SupplierInvoiceId") REFERENCES "SupplierInvoices" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "StockMovements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "MovementType" character varying(20) NOT NULL,
        "Quantity" integer NOT NULL,
        "PreviousStock" integer NOT NULL,
        "NewStock" integer NOT NULL,
        "ReferenceId" integer,
        "ReferenceType" character varying(20),
        "Notes" character varying(500),
        "CreatedBy" text,
        "CreatedDate" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_StockMovements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockMovements_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE TABLE "SaleItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SaleId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,2) NOT NULL,
        "TotalPrice" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_SaleItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SaleItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_Customers_Email" ON "Customers" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_Customers_Phone" ON "Customers" ("Phone");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Discounts_Code" ON "Discounts" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Products_SKU" ON "Products" ("SKU") WHERE SKU IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_SaleItems_ProductId" ON "SaleItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_SaleItems_SaleId" ON "SaleItems" ("SaleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_Sales_CashierId" ON "Sales" ("CashierId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_Sales_CustomerId" ON "Sales" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_Sales_PaymentMethod" ON "Sales" ("PaymentMethod");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_Sales_SaleDate" ON "Sales" ("SaleDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_Sales_Status" ON "Sales" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_StockMovements_CreatedDate" ON "StockMovements" ("CreatedDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_StockMovements_ProductId" ON "StockMovements" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_SupplierInvoiceItems_SupplierInvoiceId" ON "SupplierInvoiceItems" ("SupplierInvoiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE INDEX "IX_SupplierInvoices_InvoiceDate" ON "SupplierInvoices" ("InvoiceDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_SupplierInvoices_InvoiceNumber" ON "SupplierInvoices" ("InvoiceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430133830_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260430133830_InitialPostgres', '8.0.0');
    END IF;
END $EF$;
COMMIT;

